// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsVOqdXC-zLvol20a_uuoBhKG4CUqjmE',
    appId: '1:186798279115:web:76c3c3b4ef877c5ab24e4e',
    messagingSenderId: '186798279115',
    projectId: 'voyage-4b882',
    authDomain: 'voyage-4b882.firebaseapp.com',
    storageBucket: 'voyage-4b882.firebasestorage.app',
    measurementId: 'G-GLJRFRRYMQ',
  );

  // Configuration pour le web - à remplacer par vos propres valeurs

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmo0Bbh_vbVQSMkTzwWXhEL58rJusy9Q4',
    appId: '1:186798279115:android:f0d618042e051fd1b24e4e',
    messagingSenderId: '186798279115',
    projectId: 'voyage-4b882',
    storageBucket: 'voyage-4b882.firebasestorage.app',
  );

  // Configuration pour Android - à remplacer par vos propres valeurs

  // Configuration pour iOS - à remplacer par vos propres valeurs
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUhHU8wSJgO5MVNy95tMT07NEjzMOfz0',
    appId: '1:448618578101:ios:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'voyage-app-demo',
    storageBucket: 'voyage-app-demo.appspot.com',
    iosClientId: '448618578101-a8p7oq8u8fidn3ik0j0ea3qv1f9e9tnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}